# Generated by Django 3.0.8 on 2020-08-09 06:15

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Demo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('booked', models.ManyToManyField(blank=True, related_name='booked', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
